### ISSUE TITLE
LinuxMain stencil is based on "TestCase" not "XCTestCase"

### ISSUE THREAD

**Issue by siemensikkema** [nodes-vapor/sourcery-templates#29]
`TestCase` is something we happen to use internally but it should probably just work on subclasses of `XCTestCase`. In our projects we'd have to make sure to ignore our definition of `class TestCase: XCTestCase` using `// sourcery: excludeFromLinuxMain`.

**Comment by steffendsommer** [comment]
This sounds good to me. What do you think @BrettRToomey? If agreed, I think we should get this into the 1.0.0
